apiVersion: v1
kind: Secret
metadata:
  name: intersection-controller-secret
  namespace: uniwa-stls
type: Opaque
stringData:
  Jwt__Key: "Nn7kLa8Rzv1XHt9UwMqP4YbFdJxVt2Km"
  RabbitMQ__Username: "rabbitmq"
  RabbitMQ__Password: "rabbitmq123"
