apiVersion: v1
kind: Secret
metadata:
  name: detection-api-secret
  namespace: uniwa-stls
type: Opaque
stringData:
  Jwt__Key: "Nn7kLa8Rzv1XHt9UwMqP4YbFdJxVt2Km"
  Mongo__ConnectionString: "mongodb://mongo:mongo123@detection-db-svc:27017/"
  RabbitMQ__Username: "rabbitmq"
  RabbitMQ__Password: "rabbitmq123"

