apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: detectioncachedb
spec:
  serviceName: detectioncachedb
  replicas: 1
  selector:
    matchLabels:
      app: detectioncachedb
  template:
    metadata:
      labels:
        app: detectioncachedb
    spec:
      containers:
      - name: redis
        image: redis:7.4
        command: ["redis-server", "--appendonly", "yes"]
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: detectioncache-data
          mountPath: /data
        livenessProbe:
          exec:
            command: ["redis-cli", "ping"]
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
      volumes:
      - name: detectioncache-data
        persistentVolumeClaim:
          claimName: detectioncachedb-pvc
