apiVersion: v1
kind: ConfigMap
metadata:
  name: uniwa-stls-ids
  namespace: uniwa-stls
data:
  # Intersections
  INTERSECTION_AGIOU_SPYRIDONOS_ID: "1"
  INTERSECTION_KENTRIKI_PYLI_ID: "2"
  INTERSECTION_ANATOLIKI_PYLI_ID: "3"
  INTERSECTION_DYTIKI_PYLI_ID: "4"
  INTERSECTION_EKKLISIA_ID: "5"

  # Agiou Spyridonos (Intersection 1)
  TRAFFIC_LIGHT_AGIOU_SPYRIDONOS_DIMITSANAS_ID: "101"
  TRAFFIC_LIGHT_AGIOU_SPYRIDONOS_ID: "102"

  # Kentriki Pyli (Intersection 2)
  TRAFFIC_LIGHT_KENTRIKI_PYLI_ID: "201"
  TRAFFIC_LIGHT_KENTRIKI_PYLI_AGIOU_SPYRIDONOS_ID: "202"

  # Anatoliki Pyli (Intersection 3)
  TRAFFIC_LIGHT_ANATOLIKI_PYLI_AGIOU_SPYRIDONOS_ID: "301"
  TRAFFIC_LIGHT_ANATOLIKI_PYLI_ID: "302"

  # Dytiki Pyli (Intersection 4)
  TRAFFIC_LIGHT_DYTIKI_PYLI_ID: "401"
  TRAFFIC_LIGHT_DYTIKI_PYLI_DIMITSANAS_NORTH_ID: "402"
  TRAFFIC_LIGHT_DYTIKI_PYLI_DIMITSANAS_SOUTH_ID: "403"

  # Ekklisia (Intersection 5)
  TRAFFIC_LIGHT_EKKLISIA_KORYTSAS_ID: "501"
  TRAFFIC_LIGHT_EKKLISIA_EDESSIS_ID: "502"
  TRAFFIC_LIGHT_EKKLISIA_DIMITSANAS_ID: "503"
