apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: log-db-state
  namespace: uniwa-stls
spec:
  serviceName: log-db
  replicas: 1
  selector:
    matchLabels:
      app: log-db
  template:
    metadata:
      labels:
        app: log-db
    spec:
      containers:
        - name: log-db-container
          image: ath21/stls-databases:log-mongo
          ports:
            - containerPort: 27017
              name: mongo
          envFrom:
            - secretRef:
                name: log-db-secret
          volumeMounts:
            - name: log-db-data
              mountPath: /data/db
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: log-db-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
