apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: notification-db-state
  namespace: uniwa-stls
spec:
  serviceName: notification-db
  replicas: 1
  selector:
    matchLabels:
      app: notification-db
  template:
    metadata:
      labels:
        app: notification-db
    spec:
      containers:
        - name: notification-db-container
          image: ath21/stls-databases:notification-mongo
          ports:
            - containerPort: 27017
              name: mongo
          envFrom:
            - secretRef:
                name: notification-db-secret
          volumeMounts:
            - name: notification-db-data
              mountPath: /data/db

          resources:
            requests:
              cpu: 200m   # instead of 100-150m
              memory: 256Mi
            limits:
              cpu: 500m  # instead of 300-400m
              memory: 1Gi

          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 5

          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 10
            periodSeconds: 10

      restartPolicy: Always
      volumes:
        - name: notification-db-data
          persistentVolumeClaim:
            claimName: notification-db-pvc
