apiVersion: apps/v1
kind: Deployment
metadata:
  name: intersection-controller-agiou-spyridonos-depl
  namespace: uniwa-stls
  labels:
    app: intersection-controller-agiou-spyridonos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intersection-controller-agiou-spyridonos
  template:
    metadata:
      labels:
        app: intersection-controller-agiou-spyridonos
    spec:
      containers:
        - name: intersection-controller-agiou-spyridonos-container
          image: ath21/stls-services:intersection-controller
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: intersection-controller-config
            - secretRef:
                name: intersection-controller-secret

          env:
            - name: "Intersection__Id"
              value: "1"
            - name: "Intersection__Name"
              value: "Agiou Spyridonos"
            - name: "TrafficLights__0__Id"
              value: "101"
            - name: "TrafficLights__0__Name"
              value: "Agiou Spyridonos"
            - name: "TrafficLights__1__Id"
              value: "102"
            - name: "TrafficLights__1__Name"
              value: "Dimitsanas"

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          resources:
            requests:
              cpu: 50m   # instead of 100-150m
              memory: 128Mi
            limits:
              cpu: 200m  # instead of 300-400m
              memory: 256Mi


      restartPolicy: Always
