apiVersion: apps/v1
kind: Deployment
metadata:
  name: intersection-controller-agiou-spyridonos-depl
  namespace: uniwa-stls
  labels:
    app: intersection-controller-agiou-spyridonos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intersection-controller-agiou-spyridonos
  template:
    metadata:
      labels:
        app: intersection-controller-agiou-spyridonos
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox:1.36
          command:
            - sh
            - -c
            - >
              echo "Waiting for RabbitMQ..." &&
              until nc -z rabbitmq-svc 5672; do
                echo "RabbitMQ not ready, sleeping...";
                sleep 3;
              done;
              echo "RabbitMQ is up!"
        - name: wait-for-traffic-cache
          image: redis:7
          command:
            - sh
            - -c
            - >
              echo "Waiting for Traffic Light Cache (Redis)..." &&
              until redis-cli -h traffic-light-cache-db -a "$REDIS_PASSWORD" ping | grep -q PONG; do
                echo "Redis not ready, sleeping...";
                sleep 3;
              done;
              echo "Redis is up!"
      containers:
        - name: intersection-controller-agiou-spyridonos-container
          image: ath21/stls-services:intersection-controller
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: intersection-controller-config
            - secretRef:
                name: intersection-controller-secret

          env:
            - name: "Intersection__Id"
              value: "1"
            - name: "Intersection__Name"
              value: "Agiou Spyridonos"
            - name: "TrafficLights__0__Id"
              value: "101"
            - name: "TrafficLights__0__Name"
              value: "Agiou Spyridonos"
            - name: "TrafficLights__1__Id"
              value: "102"
            - name: "TrafficLights__1__Name"
              value: "Dimitsanas"

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          resources:
            requests:
              cpu: 50m   # instead of 100-150m
              memory: 64Mi
            limits:
              cpu: 200m  # instead of 300-400m
              memory: 128Mi


      restartPolicy: Always
