version: '3.9'

services:
  detectioncachedb:
    image: redis:7.4
    container_name: detectioncachedb
    networks:
      - detection_cache_network

networks:
  detection_cache_network:
    name: detection_cache_network
    driver: bridge
    external: true