apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: detection-db-state
  namespace: uniwa-stls
spec:
  serviceName: detection-db
  replicas: 1
  selector:
    matchLabels:
      app: detection-db
  template:
    metadata:
      labels:
        app: detection-db
    spec:
      containers:
        - name: detection-db-container
          image: ath21/stls-databases:detection-mongo
          ports:
            - containerPort: 27017
              name: mongo
          envFrom:
            - secretRef:
                name: detection-db-secret
          volumeMounts:
            - name: detection-db-data
              mountPath: /data/db
          livenessProbe:
            exec:
              command: ["mongo", "--eval", "db.adminCommand('ping')"]
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            exec:
              command: ["mongo", "--eval", "db.adminCommand('ping')"]
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
      restartPolicy: Always
      volumes:
        - name: detection-db-data
          persistentVolumeClaim:
            claimName: detection-db-pvc
