apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: detectiondb
spec:
  serviceName: detectiondb
  replicas: 1
  selector:
    matchLabels:
      app: detectiondb
  template:
    metadata:
      labels:
        app: detectiondb
    spec:
      containers:
      - name: mongo
        image: mongo:6.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: detectiondb-secret
              key: MONGO_ROOT_USERNAME
        - name: MONGO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: detectiondb-secret
              key: MONGO_ROOT_PASSWORD
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        livenessProbe:
          exec:
            command: ["mongosh", "--eval", "db.adminCommand('ping')"]
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 5
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: detectiondb-pvc