apiVersion: v1
kind: Secret
metadata:
  name: traffic-light-coordinator-secret
type: Opaque
stringData:
  Jwt__Key: Nn7kLa8Rzv1XHt9UwMqP4YbFdJxVt2Km
  MSSQL__ConnectionString: "Server=traffic-light-db-svc,1433;Database=TrafficLightDB;User Id=sa;Password=MyPass@word;TrustServerCertificate=True;"
  RabbitMQ__Username: rabbitmq
  RabbitMQ__Password: rabbitmq123
