apiVersion: v1
kind: Secret
metadata:
  name: user-api-secret
type: Opaque
stringData:
  Jwt__Key: Nn7kLa8Rzv1XHt9UwMqP4YbFdJxVt2Km
  MSSQL__ConnectionString: Server=user-db,1433;Database=UserDB;User Id=sa;Password=MyPass@word;TrustServerCertificate=True
  RabbitMQ__Username: rabbitmq
  RabbitMQ__Password: rabbitmq123
