apiVersion: v1
kind: Secret
metadata:
  name: notification-api-secret
type: Opaque
stringData:
  Jwt__Key: Nn7kLa8Rzv1XHt9UwMqP4YbFdJxVt2Km
  Email__Username: ice19390005@gmail.com
  Email__Password: waqr ilfj fxpu banq
  Mongo__ConnectionString: "mongodb://mongo:mongo123@notification-db-svc:27017"
  RabbitMQ__Username: rabbitmq
  RabbitMQ__Password: rabbitmq123
