apiVersion: v1
kind: Service
metadata:
  name: traffic-light-db-svc
  namespace: uniwa-stls
spec:
  type: ClusterIP
  ports:
    - port: 1433
      targetPort: 1433
  selector:
    app: traffic-light-db
