apiVersion: v1
kind: Secret
metadata:
  name: traffic-analytics-secret
type: Opaque
stringData:
  Jwt__Key: Nn7kLa8Rzv1XHt9UwMqP4YbFdJxVt2Km
  Mongo__ConnectionString: mongodb://mongo:mongo123@detection-db-svc:27017
  PostgreSQL__ConnectionString: Host=traffic-analytics-db-svc;Port=5432;Database=TrafficAnalyticsDB;Username=postgres;Password=postgres123
  RabbitMQ__Username: rabbitmq
  RabbitMQ__Password: rabbitmq123
