apiVersion: v1
kind: Secret
metadata:
  name: traffic-analytics-db-secret
  namespace: uniwa-stls
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres123"
  POSTGRES_DB: "TrafficAnalyticsDB"
