version: '3.9'

services:
  detectiondb:
    image: mongo:6.0
    container_name: detectiondb
    networks:
      - detection_network

networks:
  detection_network:
    name: detection_network
    driver: bridge
    external: true