apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-api-depl
  namespace: uniwa-stls
  labels:
    app: log-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-api
  template:
    metadata:
      labels:
        app: log-api
    spec:
      # === INIT CONTAINERS ===
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command: ['sh', '-c', 'until nc -z rabbitmq 5672; do echo "Waiting for RabbitMQ..."; sleep 2; done;']
        - name: wait-for-logdb
          image: busybox
          command: ['sh', '-c', 'until nc -z log-db 27017; do echo "Waiting for Log DB (Mongo)..."; sleep 2; done;']

      # === MAIN CONTAINER ===
      containers:
        - name: log-api-container
          image: ath21/stls-services:log-api
          ports:
            - containerPort: 8080
          
          envFrom:
            - configMapRef:
                name: log-api-config
            - secretRef:
                name: log-api-secret
          
          resources:
            requests:
              cpu: 50m   # instead of 100-150m
              memory: 64Mi
            limits:
              cpu: 200m  # instead of 300-400m
              memory: 128Mi
          
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
      
      restartPolicy: Always
