apiVersion: v1
kind: Secret
metadata:
  name: sensorapi-secret
  namespace: uniwa-stls
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: "mongo"
  MONGO_ROOT_PASSWORD: "mongo123"
  RABBITMQ_USERNAME: "rabbitmq"
  RABBITMQ_PASSWORD: "rabbitmq123"
  REDIS_PASSWORD: ""
  JWT_KEY: "Nn7kLa8Rzv1XHt9UwMqP4YbFdJxVt2Km"
